package com.example.statusdrafter.service;
import com.example.statusdrafter.entity.*; import com.example.statusdrafter.repository.*; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service public class TaskService {private final TaskRepository tasks; private final StatusHistoryRepository history; public TaskService(TaskRepository t,StatusHistoryRepository h){tasks=t;history=h;}
 public List<Task> mine(User u){return tasks.findByEmployeeOrderByDeadlineAsc(u);} public List<Task> recent(User u){return tasks.findTop5ByEmployeeOrderByCreatedAtDesc(u);} public Task get(Long id){return tasks.findById(id).orElseThrow(()->new NoSuchElementException("Task not found"));} public Task save(Task t){return tasks.save(t);}
 public Task update(Task incoming,User actor){Task t=get(incoming.getId()); if(!t.getEmployee().getId().equals(actor.getId()) && actor.getRole()!=User.Role.MANAGER && actor.getRole()!=User.Role.ADMIN)throw new SecurityException("Unauthorized"); Task.Status old=t.getStatus(); t.setTaskName(incoming.getTaskName());t.setDescription(incoming.getDescription());t.setProject(incoming.getProject());t.setPriority(incoming.getPriority());t.setStatus(incoming.getStatus());t.setStartDate(incoming.getStartDate());t.setDeadline(incoming.getDeadline()); Task saved=tasks.save(t); if(old!=saved.getStatus())history.save(new StatusHistory(saved,actor,old,saved.getStatus(),"Task status changed")); return saved;}
 public void delete(Long id,User actor){Task t=get(id); if(!t.getEmployee().getId().equals(actor.getId()) && actor.getRole()!=User.Role.ADMIN)throw new SecurityException("Unauthorized");tasks.delete(t);}
 public long count(User u,Task.Status s){return tasks.countByEmployeeAndStatus(u,s);} public long total(User u){return tasks.countByEmployee(u);} public long overdue(User u){return tasks.findByDeadlineBeforeAndStatusNotAndEmployeeOrderByDeadlineAsc(LocalDate.now(),Task.Status.COMPLETED,u).size();}
 public List<Task> search(String n,String e,String p,Task.Status s,Task.Priority pr,LocalDate from,LocalDate to){return tasks.search(blank(n),blank(e),blank(p),s,pr,from,to);} private String blank(String s){return s==null||s.isBlank()?null:s;}
 public List<Task> upcoming(User u){return tasks.findByDeadlineBetweenAndEmployeeOrderByDeadlineAsc(LocalDate.now(),LocalDate.now().plusDays(7),u);} public List<Task> overdueAll(){return tasks.findByDeadlineBeforeAndStatusNotOrderByDeadlineAsc(LocalDate.now(),Task.Status.COMPLETED);} }
