package com.example.statusdrafter.controller; import com.example.statusdrafter.entity.*; import com.example.statusdrafter.service.*; import jakarta.validation.Valid; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import java.util.*;
@Controller @RequestMapping("/admin") public class AdminController {final UserService users;final TaskService tasks;final ReportService reports;public AdminController(UserService u,TaskService t,ReportService r){users=u;tasks=t;reports=r;}
@GetMapping("/dashboard")String dashboard(Model m){Map<String,Long> r=reports.overall();m.addAttribute("report",r);m.addAttribute("progress",reports.percent(r));return "admin/dashboard";}
@GetMapping("/users")String users(Model m){m.addAttribute("users",users.all());m.addAttribute("roles",User.Role.values());return "admin/users";}
@PostMapping("/users")String save(@RequestParam(required=false)Long id,@RequestParam String name,@RequestParam String username,@RequestParam String email,@RequestParam User.Role role,@RequestParam(defaultValue="")String password,@RequestParam(defaultValue="true")boolean active,Model m){try{if(id==null){if(password.isBlank())throw new IllegalArgumentException("Password is required for a new user");users.create(name,username,email,password,role);}else{User u=users.all().stream().filter(x->x.getId().equals(id)).findFirst().orElseThrow();u.setName(name);u.setUsername(username);u.setEmail(email);u.setRole(role);u.setActive(active);users.save(u);}return "redirect:/admin/users?updated";}catch(Exception e){m.addAttribute("error","Unable to save user: "+e.getMessage());m.addAttribute("users",users.all());m.addAttribute("roles",User.Role.values());return "admin/users";}}
@PostMapping("/users/delete/{id}")String delete(@PathVariable Long id){users.delete(id);return "redirect:/admin/users?deleted";}
@GetMapping("/tasks")String taskList(@RequestParam(required=false)String name,@RequestParam(required=false)String employee,@RequestParam(required=false)Task.Status status,@RequestParam(required=false)Task.Priority priority,Model m){m.addAttribute("tasks",tasks.search(name,employee,null,status,priority,null,null));m.addAttribute("statuses",Task.Status.values());m.addAttribute("priorities",Task.Priority.values());return "admin/tasks";}
@GetMapping("/reports")String report(Model m){Map<String,Long> r=reports.overall();m.addAttribute("report",r);m.addAttribute("progress",reports.percent(r));return "admin/reports";}
}
