package com.example.statusdrafter.controller;
import com.example.statusdrafter.entity.*; import com.example.statusdrafter.service.*; import jakarta.validation.Valid; import org.springframework.security.core.Authentication; import org.springframework.validation.BindingResult; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*; import org.springframework.format.annotation.DateTimeFormat;
@Controller @RequestMapping("/employee") public class EmployeeController {final UserService users;final TaskService tasks;final StatusUpdateService statuses;final StatusGeneratorService generator;final ReportService reports;final NotificationService notifications;public EmployeeController(UserService u,TaskService t,StatusUpdateService s,StatusGeneratorService g,ReportService r,NotificationService n){users=u;tasks=t;statuses=s;generator=g;reports=r;notifications=n;} User me(Authentication a){return users.byUsername(a.getName());}
@GetMapping("/dashboard")String dash(Model m,Authentication a){User u=me(a);m.addAttribute("user",u);m.addAttribute("total",tasks.total(u));for(Task.Status s:Task.Status.values())m.addAttribute(s.name().toLowerCase(),tasks.count(u,s));m.addAttribute("overdue",tasks.overdue(u));m.addAttribute("recentTasks",tasks.recent(u));m.addAttribute("upcoming",tasks.upcoming(u));m.addAttribute("recentStatuses",statuses.recent(u));m.addAttribute("notifications",notifications.mine(u).stream().limit(5).toList());m.addAttribute("progress",reports.percent(reports.employee(u)));return "employee/dashboard";}
@GetMapping("/tasks")String list(Model m,Authentication a,@RequestParam(required=false)String name,@RequestParam(required=false)String project,@RequestParam(required=false)Task.Status status,@RequestParam(required=false)Task.Priority priority,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to){User u=me(a);m.addAttribute("tasks",(name==null&&project==null&&status==null&&priority==null&&from==null&&to==null)?tasks.mine(u):tasks.search(name,u.getName(),project,status,priority,from,to));m.addAttribute("statuses",Task.Status.values());m.addAttribute("priorities",Task.Priority.values());return "employee/tasks";}
@GetMapping("/tasks/add")String add(Model m,Authentication a){Task t=new Task();t.setEmployee(me(a));t.setStartDate(LocalDate.now());t.setDeadline(LocalDate.now().plusDays(7));m.addAttribute("task",t);m.addAttribute("employees",List.of(me(a)));return "employee/add-task";}
@PostMapping("/tasks/add")String save(@Valid @ModelAttribute Task t,BindingResult br,Authentication a,Model m){if(t.getStartDate()!=null&&t.getDeadline()!=null&&t.getDeadline().isBefore(t.getStartDate()))br.rejectValue("deadline","date.invalid","Deadline cannot be before start date");if(br.hasErrors()){m.addAttribute("employees",List.of(me(a)));return "employee/add-task";}t.setEmployee(me(a));tasks.save(t);return "redirect:/employee/tasks?created";}
@GetMapping("/tasks/edit/{id}")String edit(@PathVariable Long id,Model m,Authentication a){Task t=tasks.get(id);if(!t.getEmployee().getId().equals(me(a).getId()))throw new SecurityException();m.addAttribute("task",t);return "employee/edit-task";}
@PostMapping("/tasks/edit/{id}")String update(@PathVariable Long id,@Valid @ModelAttribute Task t,BindingResult br,Authentication a,Model m){t.setId(id);if(br.hasErrors())return "employee/edit-task";tasks.update(t,me(a));return "redirect:/employee/tasks?updated";}
@PostMapping("/tasks/delete/{id}")String delete(@PathVariable Long id,Authentication a){tasks.delete(id,me(a));return "redirect:/employee/tasks?deleted";}
@GetMapping("/tasks/{id}")String details(@PathVariable Long id,Model m,Authentication a){Task t=tasks.get(id);if(!t.getEmployee().getId().equals(me(a).getId()))throw new SecurityException();m.addAttribute("task",t);return "employee/task-details";}
@GetMapping("/status")String status(Model m,Authentication a){m.addAttribute("status",new StatusUpdate());m.addAttribute("today",LocalDate.now());return "employee/daily-status";}
@PostMapping("/status")String saveStatus(@Valid @ModelAttribute("status")StatusUpdate s,BindingResult br,Authentication a){if(br.hasErrors())return "employee/daily-status";statuses.save(s,me(a));return "redirect:/employee/status-history?saved";}
@GetMapping("/status/edit/{id}")String editStatus(@PathVariable Long id,Model m,Authentication a){StatusUpdate s=statuses.get(id);if(!s.getEmployee().getId().equals(me(a).getId()))throw new SecurityException();m.addAttribute("status",s);return "employee/daily-status";}
@PostMapping("/status/edit/{id}")String updateStatus(@PathVariable Long id,@Valid @ModelAttribute("status")StatusUpdate s,BindingResult br,Authentication a){if(br.hasErrors())return "employee/daily-status";s.setId(id);statuses.save(s,me(a));return "redirect:/employee/status-history?updated";}
@PostMapping("/status/delete/{id}")String deleteStatus(@PathVariable Long id,Authentication a){statuses.delete(id,me(a));return "redirect:/employee/status-history?deleted";}
@GetMapping("/status-history")String history(Model m,Authentication a,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate date){User u=me(a);List<StatusUpdate> xs=statuses.mine(u);if(date!=null)xs=xs.stream().filter(s->s.getUpdateDate().equals(date)).toList();m.addAttribute("statuses",xs);return "employee/status-history";}
@GetMapping("/status-generator")String gen(Model m,Authentication a){User u=me(a);m.addAttribute("tasks",tasks.mine(u));m.addAttribute("generated",generator.generate(u,LocalDate.now()));return "employee/status-generator";}
@PostMapping("/status-generator/generate")String generate(@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate date,@RequestParam(required=false)Set<Long> taskIds,Model m,Authentication a){User u=me(a);m.addAttribute("tasks",tasks.mine(u));m.addAttribute("generated",generator.generate(u,date,taskIds));return "employee/status-generator";}
@PostMapping("/status-generator/save")String saveGenerated(@ModelAttribute("generated")StatusUpdate s,Authentication a){statuses.save(s,me(a));return "redirect:/employee/status-history?saved";}
@GetMapping("/reports")String report(Model m,Authentication a,@RequestParam(defaultValue="monthly")String period){Map<String,Long> r=reports.employee(me(a));m.addAttribute("report",r);m.addAttribute("progress",reports.percent(r));m.addAttribute("period",reports.period(me(a),period));return "employee/reports";}
@GetMapping("/notifications")String notifs(Model m,Authentication a){m.addAttribute("notifications",notifications.mine(me(a)));return "employee/notifications";} @PostMapping("/notifications/read/{id}")String read(@PathVariable Long id,Authentication a){notifications.read(id,me(a));return "redirect:/employee/notifications";}
@GetMapping("/deadlines")String deadlines(Model m,Authentication a){User u=me(a);m.addAttribute("upcoming",tasks.upcoming(u));m.addAttribute("overdue",tasks.overdueAll().stream().filter(t->t.getEmployee().getId().equals(u.getId())).toList());return "employee/deadlines";}
@GetMapping("/profile")String profile(Model m,Authentication a){m.addAttribute("user",me(a));return "employee/profile";} @PostMapping("/profile")String profile(@ModelAttribute User form,Authentication a){User u=me(a);u.setName(form.getName());u.setEmail(form.getEmail());users.save(u);return "redirect:/employee/profile?updated";}
}
